import type { BuildingGraph } from "./schema.js";

// A simple rectangular one-story house: 8m x 6m footprint, 3m wall height,
// one door, three windows, a concrete floor slab, and a gable roof.
// This exists purely to prove the pipeline end to end in Phase 0:
// API serves it -> web app fetches it -> viewer renders it.
export const sampleBuilding: BuildingGraph = {
  id: "sample-house-01",
  name: "Sample House",
  site: {
    address: "Demo Site, Bandung, West Java, ID",
    boundary: [
      { x: -2, y: -2 },
      { x: 12, y: -2 },
      { x: 12, y: 9 },
      { x: -2, y: 9 },
    ],
  },
  levels: [{ id: "level-1", name: "Ground Floor", elevation: 0, height: 3 }],
  materials: [
    {
      id: "mat-concrete-block",
      name: "Concrete block wall",
      category: "masonry",
      unit: "m2",
      unitCost: 45,
      currency: "USD",
      densityKgM3: 1900,
      laborHoursPerUnit: 0.9,
    },
    {
      id: "mat-concrete-slab",
      name: "Reinforced concrete slab",
      category: "concrete",
      unit: "m3",
      unitCost: 180,
      currency: "USD",
      densityKgM3: 2400,
      laborHoursPerUnit: 3.2,
    },
    {
      id: "mat-roof-sheet",
      name: "Metal roof sheeting",
      category: "roofing",
      unit: "m2",
      unitCost: 22,
      currency: "USD",
      laborHoursPerUnit: 0.4,
    },
    {
      id: "mat-door-timber",
      name: "Timber panel door",
      category: "timber",
      unit: "unit",
      unitCost: 150,
      currency: "USD",
      laborHoursPerUnit: 2,
    },
    {
      id: "mat-window-alu",
      name: "Aluminium-framed window",
      category: "glazing",
      unit: "unit",
      unitCost: 220,
      currency: "USD",
      laborHoursPerUnit: 1.5,
    },
  ],
  walls: [
    {
      id: "wall-south",
      levelId: "level-1",
      start: { x: 0, y: 0 },
      end: { x: 8, y: 0 },
      height: 3,
      thickness: 0.2,
      materialId: "mat-concrete-block",
      loadBearing: true,
      openingIds: ["opening-door", "opening-window-1"],
    },
    {
      id: "wall-east",
      levelId: "level-1",
      start: { x: 8, y: 0 },
      end: { x: 8, y: 6 },
      height: 3,
      thickness: 0.2,
      materialId: "mat-concrete-block",
      loadBearing: true,
      openingIds: ["opening-window-2"],
    },
    {
      id: "wall-north",
      levelId: "level-1",
      start: { x: 8, y: 6 },
      end: { x: 0, y: 6 },
      height: 3,
      thickness: 0.2,
      materialId: "mat-concrete-block",
      loadBearing: true,
      openingIds: [],
    },
    {
      id: "wall-west",
      levelId: "level-1",
      start: { x: 0, y: 6 },
      end: { x: 0, y: 0 },
      height: 3,
      thickness: 0.2,
      materialId: "mat-concrete-block",
      loadBearing: true,
      openingIds: ["opening-window-3"],
    },
  ],
  openings: [
    {
      id: "opening-door",
      type: "door",
      wallId: "wall-south",
      offset: 3.6,
      width: 1,
      height: 2.1,
      sillHeight: 0,
    },
    {
      id: "opening-window-1",
      type: "window",
      wallId: "wall-south",
      offset: 1.2,
      width: 1.2,
      height: 1.2,
      sillHeight: 0.9,
    },
    {
      id: "opening-window-2",
      type: "window",
      wallId: "wall-east",
      offset: 3,
      width: 1.2,
      height: 1.2,
      sillHeight: 0.9,
    },
    {
      id: "opening-window-3",
      type: "window",
      wallId: "wall-west",
      offset: 3,
      width: 1.2,
      height: 1.2,
      sillHeight: 0.9,
    },
  ],
  rooms: [
    {
      id: "room-main",
      levelId: "level-1",
      boundary: [
        { x: 0, y: 0 },
        { x: 8, y: 0 },
        { x: 8, y: 6 },
        { x: 0, y: 6 },
      ],
      hasFloor: true,
      hasRoof: true,
      roofType: "gable",
      roofPitchDegrees: 22,
    },
  ],
  slabs: [
    {
      id: "slab-ground-floor",
      levelId: "level-1",
      type: "floor",
      boundary: [
        { x: 0, y: 0 },
        { x: 8, y: 0 },
        { x: 8, y: 6 },
        { x: 0, y: 6 },
      ],
      thickness: 0.12,
      materialId: "mat-concrete-slab",
    },
  ],
  roofs: [
    {
      id: "roof-main",
      levelId: "level-1",
      type: "gable",
      boundary: [
        { x: 0, y: 0 },
        { x: 8, y: 0 },
        { x: 8, y: 6 },
        { x: 0, y: 6 },
      ],
      baseHeight: 3,
      pitchDegrees: 22,
      overhang: 0.4,
      thickness: 0.15,
      materialId: "mat-roof-sheet",
    },
  ],
  columns: [],
  beams: [],
  metadata: {
    version: "0.1",
    units: "m",
    createdAt: new Date("2026-07-01T00:00:00Z").toISOString(),
    updatedAt: new Date("2026-07-01T00:00:00Z").toISOString(),
    source: "manual",
    laborRatePerHour: 25,
    disclaimer:
      "Estimation and sizing figures are preliminary and for planning purposes only. They are not a substitute for review and sign-off by a licensed architect or engineer.",
  },
};
